### ISSUE TITLE
Unkown crash

### ISSUE THREAD

**Issue by D4r33lMistaTwista** [SmithsGaming/Armory#29]
Not quite sure what's causing this...

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 7/12/16 1:13 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/smithsmodding/armory/common/item/ItemArmorComponent
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:555)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:210)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:437)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/smithsmodding/armory/common/item/ItemArmorComponent
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:64)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:546)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:524)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: com.smithsmodding.armory.common.item.ItemArmorComponent
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 36 more
Caused by: java.lang.NoClassDefFoundError: com/smithsmodding/armory/api/item/ISingleMaterialItem
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 38 more
Caused by: java.lang.ClassNotFoundException: com.smithsmodding.armory.api.item.ISingleMaterialItem
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 42 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 44 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Windows XP (x86) version 5.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 138060200 bytes (131 MB) / 344780800 bytes (328 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.28 Powered by Forge 12.17.0.1976 19 mods loaded, 19 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1976.jar) 
    UC  Forge{12.17.0.1976} [Minecraft Forge](forge-1.9.4-12.17.0.1976.jar) 
    UC  actuallyadditions{1.9.4-r45} [Actually Additions](ActuallyAdditions-1.9.4-r45.jar) 
    UC  SmithsCore{1.9.4-1.1.0.1-186} [Smiths Core](smithscore-1.9.4-1.1.0.1-186.jar) 
    UE  Armory{1.9.4-1.1.0.1-299} [Armory](armory-1.9.4-1.1.0.1-299.jar) 
    UC  endercore{1.9.4-0.4.0.26-alpha} [EnderCore](EnderCore-1.9.4-0.4.0.26-alpha.jar) 
    UC  Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UC  EnderIO{1.9.4-3.0.0.46_alpha} [Ender IO](EnderIO-1.9.4-3.0.0.46_alpha.jar) 
    UC  EnderZoo{1.9.4-1.2.2.40} [Ender Zoo](EnderZoo-1.9.4-1.2.2.40.jar) 
    UC  gravestone{1.3.1} [Gravestone](Gravestone Mod 1.3.1.jar) 
    UC  InfernalMobs{1.7.0} [Infernal Mobs](InfernalMobs-1.9.4.jar) 
    UC  itemscroller{0.5.2} [Item Scroller](itemscroller-1.10.2-0.5.2.jar) 
    UC  JEI{3.6.7.216} [Just Enough Items](jei_1.9.4-3.6.7.216.jar) 
    UC  ProjectE{1.9.4-PE1.0.4B} [ProjectE](ProjectE-1.9.4-PE1.0.4B.jar) 
    UC  roots{0.107} [Roots](roots-0.107.jar) 
    UC  RuinsAndConstructs{1.0.3} [RuinsAndConstructs](Ruins And Constructs %28v1.0.3%29.jar) 
    UC  soulshardstow{1.9.4-2.4.5-33} [Soul Shards - The Old Ways](SoulShards-TOW-1.9.4-2.4.5-33.jar) 
    UC  cavecraft{TSON Craft 3 - 1.9.4} [TSON Craft](TSON Craft 3.1.1.jar) 
    Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 8400GS/PCI/SSE2'

**Comment by marchermans** [comment]
What the heck.........
How can you not have one of the Core Item classes......

That is impossible. Can you send me the rest of the Log i need to take a look at the init order if that is possible.

**Comment by marchermans** [comment]
Ah wait, for some reason you are missing the API, that might have something todo with the restructure we are doing, let me investigate.

**Comment by marchermans** [comment]
Okey I found the issue, during the build the API did not get packaged properly, which is ofcourse a vital part which you are missing here i will see that i add it back in.

**Comment by marchermans** [comment]
New version will be live in a couple of minutes.

**Comment by marchermans** [comment]
Fixed in version: 1.1.0.1-301
