### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by crozear** [SmithsGaming/Armory#31]
Whenever I put in coal into the fireplace my game crashes, I'm running version 1.2.0.0-323 with armory weaponry version 1.3.0-53. Other than that I have tinkers construct and JEI. Heres the crash log:
java.lang.AbstractMethodError: com.smithsmodding.armory.common.tileentity.TileEntityFireplace.markDirty()V
    at com.smithsmodding.smithscore.common.inventory.IItemStorage$IInventoryWrapper.func_70296_d(IItemStorage.java:100)
    at net.minecraft.inventory.Slot.func_75218_e(Slot.java:78)
    at net.minecraft.inventory.Slot.func_75215_d(Slot.java:73)
    at net.minecraft.inventory.Container.func_184996_a(Container.java:302)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
    at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:596)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:556)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:515)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by marchermans** [comment]
I would need the complete log, i need to see the inner exceptions and stuff

**Comment by marchermans** [comment]
As i can perform the described operations properly: http://i.imgur.com/uOttILb.png

**Comment by marchermans** [comment]
As their seems to be no interest from the creator of this issue and i can not recreate it i am going to close it.
