### ISSUE TITLE
NPE when rendering inventory (FluidMoltenMetal)

### ISSUE THREAD

**Issue by melbasa** [SmithsGaming/Armory#37]
I ran into an NPE when I tried searching JEI:

java.lang.NullPointerException: Rendering screen
    at com.smithsmodding.armory.common.fluid.FluidMoltenMetal.getColor(FluidMoltenMetal.java:27)
    at com.rwtema.extrautils2.fluids.FluidColors.getColor(FluidColors.java:89)
    at com.rwtema.extrautils2.blocks.BlockDrum$1.func_186726_a(BlockDrum.java:80)
    at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:139)
    at net.minecraft.client.renderer.RenderItem.func_175032_a(RenderItem.java:217)
    at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:131)
    at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:112)
    at mezz.jei.gui.ingredients.GuiItemStackFast.renderItemAndEffectIntoGUI(GuiItemStackFast.java:99)
    at mezz.jei.gui.ingredients.GuiItemStackFastList.render(GuiItemStackFastList.java:124)
    at mezz.jei.gui.ItemListOverlay.drawScreen(ItemListOverlay.java:334)
    at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:87)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_583_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
    at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Full crash logs:
[crash-2016-09-18_12.21.15-client.txt](https://github.com/SmithsGaming/Armory/files/478824/crash-2016-09-18_12.21.15-client.txt)
[crash-2016-09-18_12.21.15-server.txt](https://github.com/SmithsGaming/Armory/files/478823/crash-2016-09-18_12.21.15-server.txt)

**Comment by marchermans** [comment]
I will try to rebuild this asap.
