### ISSUE TITLE
Can not move smiths anvil

### ISSUE THREAD

**Issue by melbasa** [SmithsGaming/Armory#38]
To reproduce:
1. Create a standard cobblestone smith's anvil (3x3x3 hit with a hammer)
2. Break the anvil with a pick
3. Place the anvil down in another location

This generates an NPE every time I load the world:

```
java.lang.NullPointerException: Ticking block entity
    at com.smithsmodding.armory.common.tileentity.state.TileEntityBlackSmithsAnvilState.writeToNBTTagCompound(TileEntityBlackSmithsAnvilState.java:107)
    at com.smithsmodding.smithscore.common.tileentity.TileEntitySmithsCore.func_189515_b(TileEntitySmithsCore.java:118)
    at com.smithsmodding.smithscore.common.tileentity.TileEntitySmithsCore.writeToSynchronizationCompound(TileEntitySmithsCore.java:340)
    at com.smithsmodding.smithscore.common.events.TileEntityDataUpdatedEvent.<init>(TileEntityDataUpdatedEvent.java:23)
    at com.smithsmodding.smithscore.common.tileentity.TileEntitySmithsCore.func_70296_d(TileEntitySmithsCore.java:146)
    at com.smithsmodding.armory.common.tileentity.TileEntityBlackSmithsAnvil.func_73660_a(TileEntityBlackSmithsAnvil.java:274)
    at net.minecraft.world.World.func_72939_s(World.java:1804)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)
```

Full crash report: [crash-2016-09-21_17.15.00-server.txt](https://github.com/SmithsGaming/Armory/files/486059/crash-2016-09-21_17.15.00-server.txt)
:

**Comment by marchermans** [comment]
Hello. i have found the problem, i will fix it, but right now i am working on the flow mechanics for Conduits.

**Comment by melbasa** [comment]
Sure, take your time.  I reloaded the previous backup and just won't move the anvil for now.

**Comment by marchermans** [comment]
Update is being released.
