### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by Xathz** [SmithsGaming/Armory#41]
[Crash when server starts up.](https://github.com/SmithsGaming/Armory/blob/Development-1.10.2/src/main/com/smithsmodding/armory/common/creativetabs/GeneralTabs.java#L14)
**Forge** 12.18.2.2107
**Armory** 1.10.2-1.2.0.0-338
**Weaponry** 1.3.0-53
**SmithsCore** 1.10.2-1.2.1-259

``` java
net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:617)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
    at com.smithsmodding.armory.common.creativetabs.GeneralTabs.<init>(GeneralTabs.java:14)
    at com.smithsmodding.armory.common.logic.ArmoryInitializer$SystemInit.registerCreativeTabs(ArmoryInitializer.java:1096)
    at com.smithsmodding.armory.common.logic.ArmoryInitializer.InitializeServer(ArmoryInitializer.java:67)
    at com.smithsmodding.armory.common.ArmoryCommonProxy.preInitializeArmory(ArmoryCommonProxy.java:32)
    at com.smithsmodding.armory.Armory.preInit(Armory.java:46)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 36 more
Caused by: java.lang.NullPointerException
```

**Comment by marchermans** [comment]
Okey i have found the problem and i have fixed it now
However i am trying to fix another bug before i release a new version.
