### ISSUE TITLE
Game crashes on armory-1.10.2-1.2.0.0-353

### ISSUE THREAD

**Issue by CKTheUltimate** [SmithsGaming/Armory#44]
Crash report:

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 11/6/16 12:50 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/smithsmodding/smithscore/util/common/helper/ItemStackHelper
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:617)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/smithsmodding/smithscore/util/common/helper/ItemStackHelper
	at com.smithsmodding.armory.common.registry.HeatableItemRegistry$ItemStackHashingStrategy.equals(HeatableItemRegistry.java:409)
	at com.smithsmodding.armory.common.registry.HeatableItemRegistry$ItemStackHashingStrategy.equals(HeatableItemRegistry.java:396)
	at gnu.trove.map.hash.TCustomHashMap.get(TCustomHashMap.java:421)
	at com.smithsmodding.armory.common.registry.HeatableItemRegistry.addStackToMap(HeatableItemRegistry.java:380)
	at com.smithsmodding.armory.common.registry.HeatableItemRegistry.addBaseStack(HeatableItemRegistry.java:170)
	at com.smithsmodding.armory.common.registry.HeatableItemRegistry.addBaseStack(HeatableItemRegistry.java:154)
	at com.smithsmodding.armory.common.material.ArmorMaterial.<init>(ArmorMaterial.java:71)
	at com.smithsmodding.armory.common.logic.ArmoryInitializer$MedievalInitialization.registerMaterials(ArmoryInitializer.java:157)
	at com.smithsmodding.armory.common.logic.ArmoryInitializer$MedievalInitialization.preInitialize(ArmoryInitializer.java:88)
	at com.smithsmodding.armory.client.logic.ArmoryClientInitializer.InitializeClient(ArmoryClientInitializer.java:52)
	at com.smithsmodding.armory.client.ArmoryClientProxy.preInitializeArmory(ArmoryClientProxy.java:172)
	at com.smithsmodding.armory.Armory.preInit(Armory.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.smithsmodding.smithscore.util.common.helper.ItemStackHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 49 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 51 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.11.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 85922424 bytes (81 MB) / 347197440 bytes (331 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 5 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2107 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2107.jar) 
	UCH	Forge{12.18.2.2107} [Minecraft Forge] (forge-1.10.2-12.18.2.2107.jar) 
	UCH	SmithsCore{1.10.2-1.2.0.0-248} [Smiths Core] (smithscore-1.10.2-1.2.0.0-248.jar) 
	UCE	Armory{1.10.2-1.2.0.0-353} [Armory] (armory-1.10.2-1.2.0.0-353.jar) 
	Loaded coremods (and transformers):

**Comment by marchermans** [comment]
You seem to be using the old SmithsCore. Please update.
