### ISSUE TITLE
minecraft crashes with smithscore-1.10.2-1.2.1-259

### ISSUE THREAD

**Issue by tdo7568** [SmithsGaming/Armory#45]
The strange thing is that Minecraft doesn't crash with smithscore-1.10.2-1.2.1-248
So here's the code:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-56.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 11/15/16 9:42 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/smithsmodding/smithscore/util/common/ItemStackHelper
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:617)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/smithsmodding/smithscore/util/common/ItemStackHelper
	at com.smithsmodding.armory.common.registry.HeatableItemRegistry$ItemStackHashingStrategy.equals(HeatableItemRegistry.java:398)
	at com.smithsmodding.armory.common.registry.HeatableItemRegistry$ItemStackHashingStrategy.equals(HeatableItemRegistry.java:385)
	at gnu.trove.map.hash.TCustomHashMap.get(TCustomHashMap.java:421)
	at com.smithsmodding.armory.common.registry.HeatableItemRegistry.addStackToMap(HeatableItemRegistry.java:368)
	at com.smithsmodding.armory.common.registry.HeatableItemRegistry.addBaseStack(HeatableItemRegistry.java:165)
	at com.smithsmodding.armory.common.registry.HeatableItemRegistry.addBaseStack(HeatableItemRegistry.java:149)
	at com.smithsmodding.armory.common.material.ArmorMaterial.<init>(ArmorMaterial.java:66)
	at com.smithsmodding.armory.common.logic.ArmoryInitializer$MedievalInitialization.registerMaterials(ArmoryInitializer.java:161)
	at com.smithsmodding.armory.common.logic.ArmoryInitializer$MedievalInitialization.preInitialize(ArmoryInitializer.java:92)
	at com.smithsmodding.armory.client.logic.ArmoryClientInitializer.InitializeClient(ArmoryClientInitializer.java:35)
	at com.smithsmodding.armory.client.ArmoryClientProxy.preInitializeArmory(ArmoryClientProxy.java:160)
	at com.smithsmodding.armory.Armory.preInit(Armory.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.smithsmodding.smithscore.util.common.ItemStackHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 50 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 266262408 bytes (253 MB) / 934105088 bytes (890 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 5 total; -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2113 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2113.jar) 
	UCH	Forge{12.18.2.2113} [Minecraft Forge] (forge-1.10.2-12.18.2.2113.jar) 
	UCH	myb{2.3.3} [myBiomes] ([1.9.4]myBiomes - Version 2.3.3.jar) 
	UCH	actuallyadditions{1.10.2-r67} [Actually Additions] (ActuallyAdditions-1.10.2-r67.jar) 
	UCH	AllThingsKevium{1.0.42} [AllThingsKevium] (AllThingsKevium-1.10.2_1.0.42.jar) 
	UCH	SmithsCore{1.10.2-1.2.1-259} [Smiths Core] (smithscore-1.10.2-1.2.1-259.jar) 
	UCE	Armory{1.10.2-1.2.0.0-335} [Armory] (armory-1.10.2-1.2.0.0-335.jar) 
	UCH	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCH	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCE	armory-weaponry{@VERSION@} [armory-weaponry] (Armory-Weaponry-1.3.0-53.jar) 
	UCH	Quark{r1.0-56} [Quark] (Quark-r1.0-56.jar) 
	UCH	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCH	Baubles{1.3.BETA11} [Baubles] (Baubles-1.10.2-1.3.BETA11.jar) 
	UCH	BiomesOPlenty{5.0.0.2091} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2091-universal.jar) 
	UCH	Botania{r1.9-335} [Botania] (Botania r1.9-335.jar) 
	UCH	cavern{1.0.8} [Cavern] (Cavern-Mod-1.10.2.jar) 
	UCH	chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-Mod-1.10.2.jar) 
	UCH	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCH	chiselsandbits{11.3} [Chisels & Bits] (chiselsandbits-11.3.jar) 
	UCH	cnoapm{1.0 by Dot_Silver} [Craftable Notch Apple Mod - MCVersion 1.10.2] (cnoapm-mcv1.10.2.jar) 
	UCH	XaeroCraftWP{1.3.1} [Craftable Waypoints] (Craftable_Waypoints_1.3.1_Forge_1.10.2.jar) 
	UCH	druidry{2016.8.10-1.9.4} [�2Druidry] (druidry(2016.8.10.2)(1.9.9).jar) 
	UCH	endercore{1.10.2-0.4.1.58-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.58-beta.jar) 
	UCH	JEI{3.12.6.304} [Just Enough Items] (jei_1.10.2-3.12.6.304.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	EnderIO{1.10.2-3.0.1.124_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.124_beta.jar) 
	UCH	excore{1.6.2} [EXCore] (Excore-1.6.2-1.10.2.jar) 
	UCH	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.2.1.jar) 
	UCH	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCH	flatcoloredblocks{mc1.10-v4.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.2.jar) 
	UCH	forestry{5.2.16.301} [Forestry] (forestry_1.10.2-5.2.16.301.jar) 
	UCH	gravestone{1.5.8} [Gravestone] (GraveStone Mod 1.5.8.jar) 
	UCH	hermitquest{1.1.22} [HermitQuest] (hermitquest-1.10.2-1.1.22.jar) 
	UCH	InventoryPets{1.4.8.2} [Inventory Pets] (inventorypets-1.10-1.4.8.2.jar) 
	UCH	jeresources{0.5.4.68} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.4.68.jar) 
	UCH	more{7.3} [M-Ore Mod] (M-Ore 7.6 1.10.2.jar) 
	UCH	Mekanism{9.2.0} [Mekanism] (Mekanism-1.10.2-9.2.0.292.jar) 
	UCH	MekanismGenerators{9.2.0} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.0.292.jar) 
	UCH	MekanismTools{9.2.0} [MekanismTools] (MekanismTools-1.10.2-9.2.0.292.jar) 
	UCH	natura{1.10.2-4.0.0.86} [Natura] (natura-1.10.2-4.0.0.86.jar) 
	UCH	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2g.jar) 
	UCH	refinedstorage{1.0.5} [Refined Storage] (refinedstorage-1.0.5.jar) 
	UCH	xreliquary{1.10.2-1.3.3.581} [Reliquary] (Reliquary-1.10.2-1.3.3.581.jar) 
	UCH	rftools{5.56} [RFTools] (rftools-1.10-5.56.jar) 
	UCH	RTG{4.1.1.6} [Realistic Terrain Generation] (RTG-1.10.2-4.1.1.6.jar) 
	UCH	shadowmc{3.4.8} [ShadowMC] (ShadowMC-1.10.2-3.4.8.jar) 
	UCH	SleepingBag{1.3.0} [Sleeping Bag] (SleepingBag-1.10.2-1.3.0.jar) 
	UCH	spawnercraft{3.1} [SpawnerCraft] (SpawnerCraft 1.10.2-3.2.0.jar) 
	UCH	taiga{1.1.4} [Tinkers Alloying Addon] (taiga-1.10.2-1.1.4.jar) 
	UCH	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCH	Torcherino{4.2s} [Torcherino] (Torcherino-4.2s.jar) 
	UCH	Waypoints{1.9.4-1.2.1} [Waypoints] (Waypoints-Mod-1.9.4.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-56.jar)
  vazkii.quark.base.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
  
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/Users/tommyhdoran/Library/Application%20Support/minecraft/mods/1.10.2/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/Users/tommyhdoran/Library/Application%20Support/minecraft/mods/1.10.2/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/Users/tommyhdoran/Library/Application%20Support/minecraft/mods/1.10.2/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/Users/tommyhdoran/Library/Application%20Support/minecraft/mods/1.10.2/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/Users/tommyhdoran/Library/Application%20Support/minecraft/mods/1.10.2/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/Users/tommyhdoran/Library/Application%20Support/minecraft/mods/1.10.2/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/Users/tommyhdoran/Library/Application%20Support/minecraft/mods/1.10.2/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/Users/tommyhdoran/Library/Application%20Support/minecraft/mods/1.10.2/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/Users/tommyhdoran/Library/Application%20Support/minecraft/mods/1.10.2/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

**Comment by marchermans** [comment]
Update armory to the newest version, a change in the sc api is causing this
